CREATE TABLE IF NOT EXISTS utente (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uq_utente_email UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS team (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    nome VARCHAR(255) NOT NULL,
    responsabile_id BIGINT NOT NULL,
    CONSTRAINT fk_team_responsabile
    FOREIGN KEY (responsabile_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS team_membro (
                                           team_id BIGINT NOT NULL,
                                           utente_id BIGINT NOT NULL,
                                           PRIMARY KEY (team_id, utente_id),
    CONSTRAINT uq_team_membro_utente UNIQUE (utente_id),
    CONSTRAINT fk_team_membro_team
    FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT fk_team_membro_utente
    FOREIGN KEY (utente_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS invito (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      team_id BIGINT NOT NULL,
                                      destinatario_id BIGINT NOT NULL,
                                      accettato BOOLEAN NOT NULL DEFAULT FALSE,
                                      CONSTRAINT fk_invito_team
                                      FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT fk_invito_destinatario
    FOREIGN KEY (destinatario_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS hackathon (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         nome VARCHAR(255) NOT NULL,
    regolamento VARCHAR(4000) NOT NULL,
    criteri_valutazione VARCHAR(4000) NOT NULL,
    scadenza_iscrizioni DATE NOT NULL,
    data_inizio DATE NOT NULL,
    data_fine DATE NOT NULL,
    luogo VARCHAR(255) NOT NULL,
    importo_premio DECIMAL(19, 2) NOT NULL,
    dimensione_massima_team INTEGER NOT NULL,
    tipo_stato VARCHAR(32) NOT NULL,
    organizzatore_id BIGINT NOT NULL,
    giudice_id BIGINT NOT NULL,
    CONSTRAINT fk_hackathon_organizzatore
    FOREIGN KEY (organizzatore_id) REFERENCES utente(id),
    CONSTRAINT fk_hackathon_giudice
    FOREIGN KEY (giudice_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS hackathon_mentore (
                                                 hackathon_id BIGINT NOT NULL,
                                                 mentore_id BIGINT NOT NULL,
                                                 PRIMARY KEY (hackathon_id, mentore_id),
    CONSTRAINT fk_hackathon_mentore_hackathon
    FOREIGN KEY (hackathon_id) REFERENCES hackathon(id),
    CONSTRAINT fk_hackathon_mentore_utente
    FOREIGN KEY (mentore_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS partecipazione (
                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              hackathon_id BIGINT NOT NULL,
                                              team_id BIGINT NOT NULL,
                                              stato VARCHAR(32) NOT NULL,
    CONSTRAINT uq_partecipazione_hackathon_team
    UNIQUE (hackathon_id, team_id),
    CONSTRAINT fk_partecipazione_hackathon
    FOREIGN KEY (hackathon_id) REFERENCES hackathon(id),
    CONSTRAINT fk_partecipazione_team
    FOREIGN KEY (team_id) REFERENCES team(id)
    );