CREATE TABLE IF NOT EXISTS utente (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uq_utente_email UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS team (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    nome VARCHAR(255) NOT NULL,
    responsabile_id BIGINT NOT NULL,
    CONSTRAINT fk_team_responsabile
    FOREIGN KEY (responsabile_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS team_membro (
                                           team_id BIGINT NOT NULL,
                                           utente_id BIGINT NOT NULL,
                                           PRIMARY KEY (team_id, utente_id),
    CONSTRAINT uq_team_membro_utente UNIQUE (utente_id),
    CONSTRAINT fk_team_membro_team
    FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT fk_team_membro_utente
    FOREIGN KEY (utente_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS invito (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      team_id BIGINT NOT NULL,
                                      destinatario_id BIGINT NOT NULL,
                                      accettato BOOLEAN NOT NULL DEFAULT FALSE,
                                      CONSTRAINT fk_invito_team
                                      FOREIGN KEY (team_id) REFERENCES team(id),
    CONSTRAINT fk_invito_destinatario
    FOREIGN KEY (destinatario_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS hackathon (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         nome VARCHAR(255) NOT NULL,
    regolamento VARCHAR(4000) NOT NULL,
    criteri_valutazione VARCHAR(4000) NOT NULL,
    scadenza_iscrizioni DATE NOT NULL,
    data_inizio DATE NOT NULL,
    data_fine DATE NOT NULL,
    luogo VARCHAR(255) NOT NULL,
    importo_premio DECIMAL(19, 2) NOT NULL,
    dimensione_massima_team INTEGER NOT NULL,
    tipo_stato VARCHAR(32) NOT NULL,
    organizzatore_id BIGINT NOT NULL,
    giudice_id BIGINT NOT NULL,
    CONSTRAINT fk_hackathon_organizzatore
    FOREIGN KEY (organizzatore_id) REFERENCES utente(id),
    CONSTRAINT fk_hackathon_giudice
    FOREIGN KEY (giudice_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS hackathon_mentore (
                                                 hackathon_id BIGINT NOT NULL,
                                                 mentore_id BIGINT NOT NULL,
                                                 PRIMARY KEY (hackathon_id, mentore_id),
    CONSTRAINT fk_hackathon_mentore_hackathon
    FOREIGN KEY (hackathon_id) REFERENCES hackathon(id),
    CONSTRAINT fk_hackathon_mentore_utente
    FOREIGN KEY (mentore_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS partecipazione (
                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              hackathon_id BIGINT NOT NULL,
                                              team_id BIGINT NOT NULL,
                                              stato VARCHAR(32) NOT NULL,
    CONSTRAINT uq_partecipazione_hackathon_team
    UNIQUE (hackathon_id, team_id),
    CONSTRAINT fk_partecipazione_hackathon
    FOREIGN KEY (hackathon_id) REFERENCES hackathon(id),
    CONSTRAINT fk_partecipazione_team
    FOREIGN KEY (team_id) REFERENCES team(id)
    );

-- Persistenza delle associazioni complete
CREATE TABLE IF NOT EXISTS sottomissione (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             partecipazione_id BIGINT NOT NULL UNIQUE,
                                             contenuto CLOB NOT NULL,
                                             CONSTRAINT fk_sottomissione_partecipazione
                                             FOREIGN KEY (partecipazione_id) REFERENCES partecipazione(id)
    );

CREATE TABLE IF NOT EXISTS valutazione (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           sottomissione_id BIGINT NOT NULL UNIQUE,
                                           giudice_id BIGINT NOT NULL,
                                           giudizio CLOB NOT NULL,
                                           punteggio DECFLOAT NOT NULL,
                                           data_ora TIMESTAMP(9) NOT NULL,
    CONSTRAINT ck_valutazione_punteggio
    CHECK (punteggio >= 0 AND punteggio <= 10),
    CONSTRAINT fk_valutazione_sottomissione
    FOREIGN KEY (sottomissione_id) REFERENCES sottomissione(id),
    CONSTRAINT fk_valutazione_giudice
    FOREIGN KEY (giudice_id) REFERENCES utente(id)
    );

CREATE TABLE IF NOT EXISTS riscossione_premio (
                                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  hackathon_id BIGINT NOT NULL UNIQUE,
                                                  stato VARCHAR(32) NOT NULL,
    beneficiary_ref VARCHAR,
    payment_ref VARCHAR,
    CONSTRAINT fk_riscossione_hackathon
    FOREIGN KEY (hackathon_id) REFERENCES hackathon(id),
    CONSTRAINT ck_riscossione_stato CHECK (
(
                                              stato = 'DA_CONFIGURARE'
                                              AND beneficiary_ref IS NULL
                                              AND payment_ref IS NULL
)
    OR (
           stato = 'PRONTA'
           AND beneficiary_ref IS NOT NULL
           AND LENGTH(TRIM(beneficiary_ref)) > 0
    AND payment_ref IS NULL
    )
    OR (
           stato = 'EROGATA'
           AND beneficiary_ref IS NOT NULL
           AND LENGTH(TRIM(beneficiary_ref)) > 0
    AND payment_ref IS NOT NULL
    AND LENGTH(TRIM(payment_ref)) > 0
    )
    )
    );

ALTER TABLE partecipazione
    ADD CONSTRAINT IF NOT EXISTS uq_partecipazione_hackathon_id
    UNIQUE (hackathon_id, id);

ALTER TABLE hackathon
    ADD COLUMN IF NOT EXISTS vincitrice_id BIGINT;

ALTER TABLE hackathon
    ADD CONSTRAINT IF NOT EXISTS fk_hackathon_vincitrice
    FOREIGN KEY (id, vincitrice_id)
    REFERENCES partecipazione(hackathon_id, id);


CREATE TABLE IF NOT EXISTS segnalazione (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            partecipazione_id BIGINT NOT NULL REFERENCES partecipazione(id),
    mentore_id BIGINT NOT NULL REFERENCES utente(id),
    descrizione CLOB NOT NULL,
    data_ora_creazione TIMESTAMP(9) NOT NULL,
    stato VARCHAR(32) NOT NULL,
    esito VARCHAR(32),
    motivazione CLOB,
    data_ora_esame TIMESTAMP(9),
    esaminatore_id BIGINT REFERENCES utente(id),
    CONSTRAINT ck_segnalazione_decisione CHECK (
(
                                                   stato = 'DA_ESAMINARE'
                                                   AND esito IS NULL
                                                   AND motivazione IS NULL
                                                   AND data_ora_esame IS NULL
                                                   AND esaminatore_id IS NULL
)
    OR
(
    stato = 'ESAMINATA'
    AND esito IS NOT NULL
    AND esito IN (
    'ARCHIVIATA',
    'VIOLAZIONE_CONFERMATA',
    'VIOLAZIONE_CON_ESCLUSIONE'
                 )
    AND motivazione IS NOT NULL
    AND LENGTH(TRIM(motivazione)) > 0
    AND data_ora_esame IS NOT NULL
    AND esaminatore_id IS NOT NULL
    )
    )
    );

CREATE TABLE IF NOT EXISTS notifica_segnalazione (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     segnalazione_id BIGINT NOT NULL UNIQUE REFERENCES segnalazione(id),
    destinatario_id BIGINT NOT NULL REFERENCES utente(id),
    data_ora_creazione TIMESTAMP(9) NOT NULL,
    letta BOOLEAN NOT NULL DEFAULT FALSE
    );